### PR TITLE
Add russian folders

### PR DESCRIPTION
**Pull request by vasylisa**
### Is the pull request based off the lastest version?
Yes

### What features have you added?
Add russian folders names

### Is your code valid PSR-2?
Yes

### CODE REVIEW

**Comment by xXXIMMATTHEWXXx** [comment]
Thank you! I would merge this but I don't know how your commit works. What does this do to enable Russian folders?

**Comment by vasylisa** [comment]
We haven't got folders _sent_ and _trash_.
So I add to arrays names of folders in UTF7-IMAP (like it returns in imap_list):
- **&bboepgrabdceoaq9bda-** in UTF8 _корзина_, that means _trash_
- **&bb4eqgq,beaemaqybdsenqq9bd0eswq1-**  in UTF8 _отправленные_, that means _sent_

**Comment by xXXIMMATTHEWXXx** [comment]
Thank you for helping out and for the or! Merged

**Comment by xXXIMMATTHEWXXx** [comment]
Once I get on computer ill merge :)

**Pull request merged**
