### PR TITLE
I think it should be better ;)

### PR DESCRIPTION
**Pull request by sergey144010**
### What bugs did you fix?
issue #74
### Optional things below
[] Added your name to the credits
[] Add a update name below:

### CODE REVIEW

**Comment by xXXIMMATTHEWXXx** [comment]
Gonna go ahead and accpet will test with composer later, if you can try and use `composer require sslience/php-imap-client dev-master`

**Comment by sergey144010** [comment]
'SSilence'
against
s**sli**ence.
and thats all.

**Comment by xXXIMMATTHEWXXx** [comment]
We do have an account for this on packagist. It has been linked. Only thing is, untill @SSilence adds packagist as a hook we have to manually update it

**Comment by sergey144010** [comment]
I dont know, but I now can see on packagist.org this package
`sslience/php-imap-client `
maybe still fix
`ssilence/php-imap-client `
and fix this
`https://packagist.org/packages/sslience/php-imap-client` ?
Maybe then it will work?

**Comment by xXXIMMATTHEWXXx** [comment]
What do you mean fix it? Just tell me what i have to do!

**Comment by sergey144010** [comment]
You are not properly registered on the pakagist package.
You did
https://packagist.org/packages/sslience/php-imap-client
Instead of
https://packagist.org/packages/ssilence/php-imap-client
Name - You did - sslience - Instead of - ssilence
Read each letters.
Change places letters L and I
now - ss->li<-ence
need - ss->il<-ence
In link and name package on https://packagist.org

**Comment by xXXIMMATTHEWXXx** [comment]
*Face plam* Thanks for noticing that. Thanks a ton :)

**Comment by xXXIMMATTHEWXXx** [comment]
Just tried to re add it. Got this error `The package name SSilence/php-imap-client is invalid, it should not contain uppercase characters. We suggest using s-silence/php-imap-client instead.`

**Comment by sergey144010** [comment]
so try just ssilence

**Comment by xXXIMMATTHEWXXx** [comment]
It reads from the repo. I can only enter the url

**Comment by sergey144010** [comment]
try delete and again add package, but ssilence

**Comment by xXXIMMATTHEWXXx** [comment]
When i add it the only thing in enter the the url

**Comment by sergey144010** [comment]
so enter https://github.com/SSilence/php-imap-client

**Comment by sergey144010** [comment]
and name ssilence

**Comment by sergey144010** [comment]
You cannot edit the current package?

**Comment by xXXIMMATTHEWXXx** [comment]
This is [what i see](http://imgur.com/a/neCQB)

**Comment by xXXIMMATTHEWXXx** [comment]
[This ](https://packagist.org/about#naming-your-package) is what packagist says should work

**Comment by xXXIMMATTHEWXXx** [comment]
Should be fixed with lastest code. Let me know

**Comment by sergey144010** [comment]
enter
https://github.com/ssilence/php-imap-client

**Comment by sergey144010** [comment]
Composer installation already running. And the pakagist package can not see. Fixed or not?

**Comment by sergey144010** [comment]
see, fixed !!! Good job !

**Pull request merged**
