### PR TITLE
Add advanced connect option

### PR DESCRIPTION
**Pull request by sergey144010**
Add advanced connect option because default connection not used a lot of imap connection options.

### CODE REVIEW

**Comment by xXXIMMATTHEWXXx** [comment]
Looks good to me

**Comment by sergey144010** [comment]
In ImapClient changed only __construct() method.
Add 4 constans, 2 vars, 
and setConnectAdvanced(), setConnectDefault(), setConnectConfig(), connectDefault(), connectAdvanced() methods. Everything else unchanged.

**Comment by xXXIMMATTHEWXXx** [comment]
Thank you for describing it better :) 👍

**Comment by sergey144010** [comment]
Need change example in to Readme and example-composer files.

**Pull request merged**
