### PR TITLE
TypeBody and TypeAttachments might as well be static methods to save …

### PR DESCRIPTION
**Pull request by hhdivil**
…time

### Is the pull request based off the lastest version?

Yes

### What features have you added?

Changed TypeBody and TypeAttachment methods to be static getters to save a few unnecessary lines of code

### What bugs did you fix?

No bugs

### Is your code valid PSR-2?

Yus

### Has anything in your pull request already been fixed?

N/A

### Anything else?

More to come, let me know if this one is cool with you

### Optional things below
[] Added your name to the credits
[] Add a update name below:

### CODE REVIEW

**Comment by xXXIMMATTHEWXXx** [comment]
Looks good!!!!!

**Comment by sergey144010** [comment]
This step in the future will add additional problems.

**Comment by hhdivil** [comment]
Yeah I did you a pull req. for the bug - it was a missing $ :( Sorry

**Comment by sergey144010** [comment]
I mean a static challenge.

**Comment by hhdivil** [comment]
What do you mean by that?

**Comment by sergey144010** [comment]
By doing so, you remove the possibility in the future of an easier set up of TypeBody and TypeAttachments. If you need more detailed work with types, and most likely it will be needed, you will have to return everything back.

**Pull request merged**
