### PR TITLE
setFlag methods

### PR DESCRIPTION
**Pull request by reimax**
in ImapClient.php add:

```php
     /**
     * Set flag message
     *
     * @param int $ids or string like 1,2,3,4,5 or string like 1:5
     * @return bool
     */
    public function setFlagMessage($ids, $flags)
    {
        // We need better docs for this
        return imap_setflag_full($this->imap, $ids, $flags, ST_UID);
    }

    /**
     * Unset flag message
     *
     * @param int $ids or string like 1,2,3,4,5 or string like 1:5
     * @return bool
     */
    public function unsetFlagMessage($ids, $flags)
    {
        // We need better docs for this
        return imap_clearflag_full($this->imap, $ids, $flags, ST_UID);
    }
```

and use:
```php
$imap->setFlagMessage(message_uid, message_flag);

$imap->unsetFlagMessage(message_uid, message_flag);
```

default setUnseenMessage() not work since there is no additional option ST_UID.
[http://php.net/manual/ru/function.imap-clearflag-full.php](url)

### CODE REVIEW

**Comment by xXXIMMATTHEWXXx** [comment]
Hey! We have some issues, please fix the conflicts before I merge!

**Comment by reimax** [comment]
I only added two methods, conflicts with existing code I not have.

**Comment by xXXIMMATTHEWXXx** [comment]
When attempting to merge I can granted with conflicts. In order to fix this please remake a new clone, commit the code again and then I will merge this

**Comment by reimax** [comment]
I gave a working solution for a problem. The merge issue nothing to do with my decision. How to resolve these dependencies I do not see. My request is why it got to one that already existed. Mistakes in prev pull are not my mistakes, I didn't make edits on the code in the main library.

**Comment by xXXIMMATTHEWXXx** [comment]
Okay, I will handle and fix this later

**Comment by xXXIMMATTHEWXXx** [comment]
Fixed the issue. Merged.

**Comment by reimax** [comment]
setFlagMessage(), unsetFlagMessage() not add.

**Pull request merged**
